#!/usr/bin/env bash
# One-time staging environment provisioning (issue #868).
#
# Runs on a DEDICATED staging host — NOT the production Pi. This is
# deliberate: CONTROL_PLANE_CONTRACT.md I1 says only deploy.yml (or POP
# Executor) may execute changes on the production box; a second SSH path
# onto that box would need a formal [contract-change] PR. A separate host
# sidesteps that boundary instead of reopening it.
#
# This script is NOT run by CI or by any agent — a human runs it once,
# interactively, on the fresh staging host. Completing it does NOT prove
# that a public staging URL, GitHub staging environment, or auto-deploy
# path exists; see docs/GUIDE_STAGING_ENVIRONMENT.md.
#
# Prerequisites (Debian 12 / bookworm — match production runtime):
#   Apache 2.4, PHP 8.2-FPM, MariaDB 10.11, Composer 2, Node 22 (for later
#   frontend builds), git, openssl. Install steps live in the guide; this
#   script only checks and configures.
#
# Usage (on the staging host):
#   bash scripts/infra/setup-staging-env.sh <git-remote-url>
set -euo pipefail

REPO_URL="${1:?Usage: setup-staging-env.sh <git-remote-url>}"
STAGING_DIR=/home/staging/AllTrue_System
STAGING_DB=AllTrue_staging
STAGING_DB_USERNAME="atr_staging"
APACHE_SITE=alltrue-staging
PHP_FPM_SOCK=/run/php/php8.2-fpm.sock

require_cmd() {
  if ! command -v "$1" >/dev/null 2>&1; then
    echo "ERROR: missing required command '$1'." >&2
    echo "Install the Debian 12 staging stack first — see docs/GUIDE_STAGING_ENVIRONMENT.md §1a." >&2
    exit 1
  fi
}

echo "=== [0/4] Prerequisite checks (Debian 12 parity) ==="
require_cmd git
require_cmd openssl
require_cmd mysql
require_cmd php
require_cmd composer
require_cmd apache2ctl
require_cmd systemctl

if [[ ! -S "$PHP_FPM_SOCK" ]]; then
  echo "ERROR: PHP 8.2-FPM socket not found at $PHP_FPM_SOCK." >&2
  echo "Install/enable php8.2-fpm before running this script." >&2
  exit 1
fi

PHP_MAJOR_MINOR="$(php -r 'echo PHP_MAJOR_VERSION.".".PHP_MINOR_VERSION;')"
if [[ "$PHP_MAJOR_MINOR" != "8.2" ]]; then
  echo "ERROR: expected PHP 8.2.x, found $(php -v | head -1)." >&2
  exit 1
fi

if ! php -m | grep -qi '^pdo_mysql$'; then
  echo "ERROR: php8.2-mysql (pdo_mysql) extension is required." >&2
  exit 1
fi

# MariaDB client still ships as `mysql`; accept MariaDB or MySQL-compatible.
DB_VERSION_LINE="$(mysql --version 2>/dev/null || true)"
if ! grep -qiE 'MariaDB|Distrib 10\.|Ver 8\.' <<<"$DB_VERSION_LINE"; then
  echo "WARN: unexpected mysql client banner: $DB_VERSION_LINE" >&2
fi
echo "✅ Prerequisites look present"
echo "   php=$(php -v | head -1)"
echo "   db=$DB_VERSION_LINE"
echo "   apache=$(apache2ctl -v 2>/dev/null | head -1 || apache2 -v | head -1)"

echo "=== [1/4] Staging code directory ==="
if [ -d "$STAGING_DIR/.git" ]; then
  echo "✅ $STAGING_DIR already a git checkout, skipping clone"
else
  mkdir -p /home/staging
  git clone "$REPO_URL" "$STAGING_DIR"
  echo "✅ Cloned into $STAGING_DIR"
fi

echo "=== [2/4] Staging MariaDB database + least-privilege user ==="
STAGING_DB_PASSWORD="$(openssl rand -hex 24)"
# Interactive root auth — never reuse production credentials here.
mysql -u root -p <<SQL
CREATE DATABASE IF NOT EXISTS \`${STAGING_DB}\` CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
CREATE USER IF NOT EXISTS '${STAGING_DB_USERNAME}'@'localhost' IDENTIFIED BY '${STAGING_DB_PASSWORD}';
CREATE USER IF NOT EXISTS '${STAGING_DB_USERNAME}'@'127.0.0.1' IDENTIFIED BY '${STAGING_DB_PASSWORD}';
GRANT ALL PRIVILEGES ON \`${STAGING_DB}\`.* TO '${STAGING_DB_USERNAME}'@'localhost';
GRANT ALL PRIVILEGES ON \`${STAGING_DB}\`.* TO '${STAGING_DB_USERNAME}'@'127.0.0.1';
FLUSH PRIVILEGES;
SQL
echo "✅ Database ${STAGING_DB} + user ${STAGING_DB_USERNAME} created (localhost + 127.0.0.1)"

echo "=== [3/4] Apache vhost on port 80 (staging-only host; PHP 8.2-FPM) ==="
APACHE_CONF="/etc/apache2/sites-available/${APACHE_SITE}.conf"
sudo tee "$APACHE_CONF" >/dev/null <<APACHE
# Generated by scripts/infra/setup-staging-env.sh — staging host only.
<VirtualHost *:80>
    ServerName _
    DocumentRoot ${STAGING_DIR}/backend/public

    <Directory ${STAGING_DIR}/backend/public>
        Options -Indexes +FollowSymLinks
        AllowOverride All
        Require all granted
    </Directory>

    <FilesMatch \\.php\$>
        SetHandler "proxy:unix:${PHP_FPM_SOCK}|fcgi://localhost"
    </FilesMatch>

    ErrorLog \${APACHE_LOG_DIR}/${APACHE_SITE}-error.log
    CustomLog \${APACHE_LOG_DIR}/${APACHE_SITE}-access.log combined
</VirtualHost>
APACHE

sudo a2enmod rewrite proxy_fcgi setenvif >/dev/null
sudo a2enconf php8.2-fpm >/dev/null || true
sudo a2dissite 000-default >/dev/null 2>&1 || true
sudo a2ensite "$APACHE_SITE" >/dev/null
sudo apache2ctl configtest
sudo systemctl reload apache2
echo "✅ Apache vhost ${APACHE_SITE} active on port 80 (DocumentRoot → backend/public, php8.2-fpm)"

echo "=== [4/4] Next steps (manual, credential-sensitive) ==="
cat <<NEXT

Provisioning finished on this host only. It does NOT create GitHub Environments,
auto-deploy, or prove a public staging URL exists.

1. Generate a dedicated deploy SSH key for THIS host (do not reuse PI_SSH_KEY):
     ssh-keygen -t ed25519 -f ~/.ssh/staging_deploy -C "github-actions-staging-deploy" -N ""
     cat ~/.ssh/staging_deploy.pub >> ~/.ssh/authorized_keys

2. From your own machine, add staging-only secrets to the GitHub *staging*
   environment (see docs/runbooks/GITHUB_ENVIRONMENTS_SETUP.md) — not production:
     gh secret set STAGING_SSH_HOST --env staging --body '<this host IP or hostname>'
     gh secret set STAGING_SSH_USER --env staging --body '<the user you SSH as>'
     gh secret set STAGING_SSH_KEY  --env staging --body "\$(base64 -w0 ~/.ssh/staging_deploy)"
     gh secret set STAGING_DB_USERNAME --env staging --body '${STAGING_DB_USERNAME}'
     gh secret set STAGING_DB_PASSWORD --env staging --body '${STAGING_DB_PASSWORD}'

3. Copy backend/.env.example to ${STAGING_DIR}/backend/.env and fill in:
     APP_ENV=staging
     DB_CONNECTION=mysql
     DB_HOST=127.0.0.1
     DB_DATABASE=${STAGING_DB}
     DB_USERNAME=${STAGING_DB_USERNAME}
     DB_PASSWORD=${STAGING_DB_PASSWORD}
   Do not copy production .env or PI_* credentials.

4. Manual deploy (auto-deploy workflow is NOT set up — control-plane I1):
     cd ${STAGING_DIR} && git fetch origin && git reset --hard origin/main
     cd backend && composer install --no-interaction --prefer-dist
     php artisan migrate --force
     cd ../frontend && npm ci && npm run build
     sudo systemctl reload php8.2-fpm

5. Smoke (no production SMOKE_* credentials):
     curl -fsS http://127.0.0.1/api/v1/health
     curl -fsS http://127.0.0.1/deployment.json

Full lifecycle: docs/GUIDE_STAGING_ENVIRONMENT.md
NEXT
