#!/usr/bin/env python3
"""Generate docs/catalog/SERVICES_INDEX.md from services.json."""
from __future__ import annotations

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
CATALOG = ROOT / "docs/catalog/services.json"
OUT = ROOT / "docs/catalog/SERVICES_INDEX.md"


def main() -> None:
    data = json.loads(CATALOG.read_text(encoding="utf-8"))
    lines = [
        "# Service Catalog Index (generated)",
        "",
        f"**Source:** `docs/catalog/services.json` (v{data.get('version')})",
        f"**Last verified:** {data.get('last_verified')}",
        f"**Owner:** {data.get('owner')}",
        "",
        "Do not edit this file by hand — run `make catalog-index`.",
        "",
        "| ID | Product | Name | Owner | Lifecycle | Runbook | Deploy |",
        "|----|---------|------|-------|-----------|---------|--------|",
    ]
    for s in data.get("services") or []:
        lines.append(
            f"| `{s['id']}` | {s['product']} | {s.get('name', '')} | {s.get('owner', '')} | "
            f"{s.get('lifecycle', '')} | `{s.get('runbook', '')}` | `{s.get('deployment_workflow', '')}` |"
        )
    lines.append("")
    OUT.write_text("\n".join(lines), encoding="utf-8")
    print(f"Wrote {OUT}")


if __name__ == "__main__":
    main()
